name: easy-start-actions
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      -  run: npm i
      -  run: npm test
      -  run: npm run release
      -  run: git push --follow-tags origin main && npm publish